name: Deploy Docker

on:
  push:
    branches:
      - main
env:
  CACHE_KEY: node-deps        
  MONGODB_DB_NAME: gha-demo
  MONGODB_USERNAME: sumit8340  
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container:
        image: node:16
        
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: cluster0.rbjguts.mongodb.net  
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080  
    steps:
      - name: Get codes
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY}}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci          
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: 
          echo "MONGODB_USERNAME:${{ env.MONGODB_USERNAME }}"  

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: 
          echo "MONGODB_USERNAME:${{ env.MONGODB_USERNAME }}"
          
